// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrLfy8hcMIoCM3QKB6cwE7-_JSJvG9AkI',
    appId: '1:1024940266281:web:1d457ebf29e8220208dd38',
    messagingSenderId: '1024940266281',
    projectId: 'rechatapp-ea29e',
    authDomain: 'rechatapp-ea29e.firebaseapp.com',
    storageBucket: 'rechatapp-ea29e.appspot.com',
    measurementId: 'G-0NMBXCEKYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3n2fWGMqwYRW_ML1Pz2btbeBS_bybM4',
    appId: '1:1024940266281:android:b0fe8df45ea89fc408dd38',
    messagingSenderId: '1024940266281',
    projectId: 'rechatapp-ea29e',
    storageBucket: 'rechatapp-ea29e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYC5zbJPIga5UPVsXw3xoMzyXxVjrYFQE',
    appId: '1:1024940266281:ios:026a8db63b4a5a9308dd38',
    messagingSenderId: '1024940266281',
    projectId: 'rechatapp-ea29e',
    storageBucket: 'rechatapp-ea29e.appspot.com',
    androidClientId: '1024940266281-1n9kvhu7tpj9jefrkhubcsfh5qc49rd2.apps.googleusercontent.com',
    iosClientId: '1024940266281-n1hp3pknl1uolelfcgis5m687oh1dl7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.rechatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYC5zbJPIga5UPVsXw3xoMzyXxVjrYFQE',
    appId: '1:1024940266281:ios:4395643d2d64214308dd38',
    messagingSenderId: '1024940266281',
    projectId: 'rechatapp-ea29e',
    storageBucket: 'rechatapp-ea29e.appspot.com',
    androidClientId: '1024940266281-1n9kvhu7tpj9jefrkhubcsfh5qc49rd2.apps.googleusercontent.com',
    iosClientId: '1024940266281-nh9va3ipvbb95om8g76bnnj6b4ibn4ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.rechatFirebase.RunnerTests',
  );
}
